name: Update Emote Configuration

on:
  push:
    paths:
      - 'emotes/img/**'

jobs:
  update-config:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Generate emote config
        run: node scripts/generate-emote-config.js
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add emotes/emote_config.json
          git diff --staged --quiet || (git commit -m "Update emote configuration" && git push)
